### ISSUE TITLE
[Feature Request]: Implement Stream Browser

### ISSUE THREAD

**Issue by ozziej** [RedisInsight/RedisInsight#112]
**Problem description** Please can you implement stream browsers

**How often do you encounter this problem** Always

**Alternatives considered** cli / redis-insights v1

**Additional information** Just add it.

**Comment by kijanawoodard** [comment]
I imagine that this request is deceptively complex. 

Looking at the output in Redis Insight v1 and Another Redis Desktop Manager shows that displaying a grid of values on arbitrary name value collections prompts some interesting design tradeoffs.

On the other hand, there are probably some information that are easier to achieve around number of messages, consumer groups, consumers, etc.

I'd be interested to know what the team feels are hurdles.

Redis Insight v1 becomes unusable after 100k messages. It simply won't load them.
Before that point, displaying data from a heterogenous collection is a bit unwieldy.

Another Redis Desktop Manager handles large collections a bit better by paging, but displays the name values as json. I still need to test what they do when there are repeated keys.

For the moment, we're using the CLI once a stream gets large.

**Comment by ViktarStarastsenka** [comment]
Hi @ozziej and @kijanawoodard , currently Streams are in design and I would like to get your thoughts and ideas about the current design option.
you can find it here:
https://xd.adobe.com/view/1daf6939-0d98-4357-a223-d8f4cf15d8d9-48fc/

Some highlights (please note, they are only ideas for now):

- Streams will be available in Browser
- You can filter by entry ID
- Set auto-refresh time
- Switch to text view if you have a heterogenous collection
- Add new entries

Also we plan to support Consumer Groups as well.

**Comment by ozziej** [comment]
Thanks, this is excellent, I've added some comments on the Adobe link.

**Comment by naumf** [comment]
Hi @ViktarStarastsenka, I also want to share my thoughts regarding the streams feature due to the issues I had with RedisInsight v1. 

Same as @kijanawoodard and @ozziej said, once there is too much data, the app freezes, making it unusable and the CLI must be used.

I saw the design and I like it a lot. I also read the comments there (on the provided Adobe XD link) about using virtualized libraries which is excellent, since it would solve the first part of the problem (if app freezes due to too many entries).

My concerns are regarding the second part of the problem, as @ozziej said what if there is a single field (i.e. Message, as per this design https://xd.adobe.com/view/1daf6939-0d98-4357-a223-d8f4cf15d8d9-48fc/screen/022a0c7d-b510-4b3d-b744-e1a74484871e) and it contains a JSON data, larger than 1MB.

The first thing that comes to my mind is to check if the string has more chars than specified (i.e. 256 or 512) and If longer than that here are a few ideas:
- show the first N chars of the string in the list view (where all entries of the stream are listed) and once a specific entry is clicked to open a detail view showing the whole message and of course the remaining fields and values of the selected entry.
- instead of showing the actual message, show a warning message that the string is too large and the user has to download it or view it in a dialog view. Maybe another icon could be added before the trash icon for this use-case.

**Comment by ViktarStarastsenka** [comment]
Please check the support for Redis Streams in V2.2.0 (Consumer Groups will be added later).

**Comment by naumf** [comment]
Thanks for the hard work, it is pretty good, fast and stable.
The only feature that's missing right now is the entry's detail view or a copy to clipboard button for each entry (possible location: before the trash button). 
It is needed in order to get the entry's full text value instead of the truncated one.

**Comment by ozziej** [comment]
Works pretty well so far. I agree that it does need a "click for detail" view. (even a popup dialog would be fine)
