### ISSUE TITLE
[Bug]: MEMORY USAGE BY KEY table showing keys with no expiry that can't be retrieved

### ISSUE THREAD

**Issue by carltondickson** [RedisInsight/RedisInsight#1158]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).

* Ran a memory analysis on a large DB (10GB file, 18GB once imported)  using Redis Insights 1
* I get a list of large non expiring keys
* Clicking on the largest keys of type **string** results in an error when trying to open the key, as if it doesn't exist - Have tried querying redis using CLI from Redis Insights 2
* This works fine for keys that are **sets**

![export](https://user-images.githubusercontent.com/1442885/190381044-ffaec9c3-5848-4f9e-a58b-2a4dee3be99d.png)

**How often do you encounter this problem** (Describe how frequently this problem occurs).

For the majority of **string** keys that are displayed in the "MEMORY USAGE BY KEY" table

**Alternatives considered** (Describe any alternative features or products you've considered).

-

**Additional information** (Add any other context or details here).

If memory analysis has identified these keys as not having an expiry time, they should be retrievable using GET key shouldn't they?
My production DB was exported to a dump.rdb file and I'm using that for the offline analysis.

**Comment by GnaneshKunal** [comment]
Hey @carltondickson,

Here are some information about V1:
- V1 Browser tool shows only the keys that are available in the redis.
- V1 Memory Analysis:
    - Online — Analyses what's on the redis
    - Offline — Analyses the provided RDB without importing the data into current redis instance.
    - Summary — Shows overview of the analysis. Also gives a hyper link to each key that redirects to the browser.

Since you have mentioned that you have done a dump.rdb file export and used it for offline analysis, when you click a key on the summary of memory analysis, redisinsight tries to view the data of the key in the Browser tool but that key doesn't exist.

Also, the rdb file might still contain expired keys (for a very short amount of time) which wasn't removed, so the analysis does show the expired keys but they aren't removed but when tried searching the same in the browser tool, which asks redis for the key, redis simply says the key is not found.

Also there's no extra handling done in Browser tool. Browser tool simply asks redis for the key. Also try out the CLI tool and query for the same key, if CLI and Browser says the keys aren't present then they aren't present.

**Comment by carltondickson** [comment]
@GnaneshKunal thanks for the info 👍🏽
