### ISSUE TITLE
[Feature Request]:Context-path support

### ISSUE THREAD

**Issue by Simbafa** [RedisInsight/RedisInsight#1477]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).

Context-path is required when RedisInsight is used behind a gateway in a micro-service system.

**How often do you encounter this problem** (Describe how frequently this problem occurs).

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).

**Comment by abdulk1** [comment]
Not sure who to ask -- @ViktarStarastsenka - any update on this? We'd like to use RedisInsight on this own path but it doesn't seem to work. 

The page load but none of the js/css. Should there be an environment variable to set the base href? Because right now it's looking for the js/css at <HOST> instead of <HOST>/insight

![image](https://github.com/RedisInsight/RedisInsight/assets/27826168/4bfda91c-f624-4894-8806-a7017d75b145)

**Comment by ViktarStarastsenka** [comment]
hi @abdulk1 , we are planning to release the subpath proxy support with 2.46 (in late March).

**Comment by ViktarStarastsenka** [comment]
the subpath proxy support is a bit delayed till 2.48 (late April), the progress is tracked there - 
https://github.com/RedisInsight/RedisInsight/issues/1937#issuecomment-2018319858
