### ISSUE TITLE
[Bug]: Graph View and Table view different 

### ISSUE THREAD

**Issue by alperensayar** [RedisInsight/RedisInsight#1700]
<img width="396" alt="Ekran Resmi 2023-02-07 22 01 23" src="https://user-images.githubusercontent.com/56897887/217340538-cd398538-2c73-424e-a9d2-a84d52f84d8d.png">
its my graph view and 
its my cypher query = "MATCH (n)-[r1:kesideci]->(m)-[r2:kesideci]->(o)-[r3:kesideci]->(n)
where n.id = '12055727'
RETURN n, m,o,[r1,r2,r3]"

for this query table view just have 3 edges doesn't have 5 edges.
btw when I run this code
"result22 = r.execute_command("GRAPH.QUERY", "tf","MATCH (n)-[r1:kesideci]->(m)-[r2:kesideci]->(o)-[r3:kesideci]->(n) where n.id = '12055727' RETURN n, m,o,r1,r2,r3")

result_list = []
for row in result22[1]:
    #result_list.append({k.decode(): v.decode() if isinstance(v, (bytes, bytearray)) else v for k, v in zip(result[0], row)})
    result_list.append({k.decode(): v.decode() if isinstance(v, bytes) else v for k, v in zip(result22[0], row)})"
it doesn't return 5 edges just 3. What is the difference from graph view and table view or code response? Why table view doesn't show some edges?

**Comment by GnaneshKunal** [comment]
@alperensayar 

This is not a bug but the Graph view is enhanced in terms of UX.

Table view: Shows the output of the query.
Graph view: Output + additional edges (auto-fetched). These extra edges can be toggled via a switch at the top right.

**Comment by alperensayar** [comment]
thanks four your response. I am writing a python code and using redis and redis graph libraries.
To get same response and visualize with redis insight how can I write this query? 

redis_graph = Graph("denetim_aylik_son", redis_connection)
query = "MATCH (n)-[r1:kesideci]->(m)-[r2:kesideci]->(o)-[r3:kesideci]->(n) where n.id = '12055727' RETURN n, m,o,[r1,r2,r3]"
query_result2 = redis_graph.query(
print("query_result2: ", len(query_result2.result_set))
Thanks for now.

**Comment by GnaneshKunal** [comment]
Hey @alperensayar, 

Your query is straight forward and tries to get the path (nodes + edges) for node where its `id` = `12055727`. Objects returned have entities of only this path.

In the Graph View of RedisInsight, we also try to retrieve edges that are not in the query set (, nodes that are in the view, but their edges are not because they are not returned to the result set). If you want those edges, they will have to be returned.

We use the following queries:
https://github.com/RedisInsight/RedisInsight/blob/main/redisinsight/ui/src/packages/redisgraph/src/utils.ts#L204-L211
