### ISSUE TITLE
Why is the UI compiled from the source code (2.0.3-preview) completely inconsistent with the UI of the docker hub (1.11.0), and the source code compilation lacks many functions

### ISSUE THREAD

**Issue by baozitao** [RedisInsight/RedisInsight#178]
Why is the UI compiled from the source code (2.0.3-preview) completely inconsistent with the UI of the docker hub (1.11.0), and the source code compilation lacks many functions？

this is docker hub V1.11.0
![Capture](https://user-images.githubusercontent.com/47717122/147953565-0c2e03cb-82b6-4830-8817-4e31fdda27e1.PNG)

this is compiled from the source code (2.0.3-preview)
![Capture1](https://user-images.githubusercontent.com/47717122/147953810-4f0d1f4f-6576-43ed-bcac-b60cc7053032.PNG)

**Comment by ViktorStarostenko** [comment]
Hello @baozitao.
RedisInsight 2.0 is a complete product rewrite with the updated design, this is the reason for different UI.
Indeed RedisInsight 2.0 does not have all the features from v. 1.0 so far, since this is just the start of the journey.
Find more information and plans for the future here: https://redis.com/blog/introducing-redisinsight-2/.

Please let us know if you love any particular features from v. 1.0 and would like to see them in v. 2.0 as well.

**Comment by baozitao** [comment]
> Will redisinsight 2.0 have an open source plan?

**Comment by ViktarStarastsenka** [comment]
@baozitao , right now it is a source-available plan and it will not change in the upcoming months for sure.
