### ISSUE TITLE
连接云数据库持续出现error[Bug]:

### ISSUE THREAD

**Issue by Gu-1Mi** [RedisInsight/RedisInsight#2668]
**Preconditions** (Any important steps we need to know)
1.打开RedisInsight

**Steps to reproduce** (How to reproduce what you found step by step)

**Actual behavior** (A short description of what you found)

**Expected behavior** (A short description of what you expected to find)
点击页面链接后能正常登录返回RedisInsight登录

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://github.com/RedisInsight/RedisInsight/assets/105277401/136b418a-27f1-4ec3-bf9d-043f4134ff94)

![image](https://github.com/RedisInsight/RedisInsight/assets/105277401/253d1c97-532b-4aa2-9007-fe1446d1f7d1)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
window11,RedisInsight-v2(2.34)

**Comment by ViktarStarastsenka** [comment]
hi @Gu-1Mi , can you please describe your detailed steps to receive this error?
this information will help to investigate the root cause.

**Comment by wego1236** [comment]
Preconditions (Any important steps we need to know)
1. open RedisInsight

Steps to reproduce (How to reproduce what you found step by step)
1. click Redis cloud: your ultimate Redis starting point
2. click sign up with github
<img width="862" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/56502074/7216b460-23fa-40b2-83bc-ac4a0a2545d3">
4.  sign up After success,  need to jump to
<img width="840" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/56502074/9a5394c7-a672-4ae3-87b6-e03f7eb79afa">
5. Error after the jump
<img width="1078" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/56502074/5e4ba8f5-0ee5-446d-b4a3-a2bf296568d9">

Expected behavior (A short description of what you expected to find)
点击页面链接后能正常登录返回RedisInsight登录

Additional context (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
MacOs ，RedisInsight-v2(2.34)

**Comment by arthosofteq** [comment]
@wego1236 could you look at the url on the redirect page (with the blue "Open RedisInsight" button)? There should be error details in the query parameters

**Comment by wego1236** [comment]
the url is https://auth.redisinsight.redis.com/callback.html?state=lXnVdllPQqDCo4rO3YZVQDP59pPhwfDxjloNadCKwRl09ildGfOrS9WGc3ebFpB0&error=access_denied&error_description=The+following+required+property+is+missing%3A+%27email%27.#success

the error description The+following+required+property+is+missing%3A+%27email%27.#success

**Comment by ViktarStarastsenka** [comment]
please re-open the ticket if the issue still reproduces.
