### ISSUE TITLE
[Bug]:not been able to login to add server for redis insight while running from docker 

### ISSUE THREAD

**Issue by deepjyoti-clirnet** [RedisInsight/RedisInsight#3641]
not been able to connect vpc running in the same VM. unable to add other database while adding it manually while running using container for Redis insight

**Comment by ViktarStarastsenka** [comment]
@deepjyoti-clirnet , provide more details about your setup and the error.

**Comment by junhyeongkim2** [comment]
I have the Similar issue. I ran Redis and Redis Insight with Docker Compose, and the connection to host.docker.internal:6379 is fine through Redis Insight, but the values ​​stored in the connected docker Redis are not loaded at all. Even if I store the value in the same index through SET and test it, there is no value. 
I'm wondering if there's something I did wrong, Thank you.

+And when I first connect redis Insight, this strange value appears, but I don't know what it is. Because my Redis is empty.
Even if I delete volume, image, container just in case, the same values ​​remain.


<img width="687" alt="스크린샷 2024-08-03 오후 11 56 07" src="https://github.com/user-attachments/assets/3c304d49-a5bc-458a-b488-3ddde82a1d55">
<img width="1299" alt="스크린샷 2024-08-03 오후 11 56 21" src="https://github.com/user-attachments/assets/fcfe6b71-0cae-44f1-a75d-1eed38ff90ce">


1. redis insight connect

host : host.docker.internal
port : 6379

3. my docker-compose 

  redis:
    container_name: campride_redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - campride_network
      - app-tier

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - "5540:5540"

**Comment by ViktarStarastsenka** [comment]
@deepjyoti-clirnet , re-open the ticket if this still reproduces.

**Comment by ViktarStarastsenka** [comment]
hi @voodoodror , currently, SSO is not supported in Docker builds.

**Comment by voodoodror** [comment]
@ViktarStarastsenka Thanks for the quick response! Is there a plan to support it in the future?

**Comment by ViktarStarastsenka** [comment]
@voodoodror , there is a technical limitation so I can't provide a timeline at the moment.
We'd be happy to add it eventually.
