### ISSUE TITLE
[Bug]: redis-cluster - can't rename key

### ISSUE THREAD

**Issue by raphaelauv** [RedisInsight/RedisInsight#3683]
with redis-cluster if I rename a key

```log
CROSSSLOT Keys in request don't hash to the same slot
```

redis insight should allow me to rename a key even it the new key end in a different slot.

Thanks

**Comment by kchepikava** [comment]
@raphaelauv, unfortunately we cannot provide any fix for this since it is a redis restriction in a cluster mode. Your old key and new key must be in the same hash slot to have the ability to change it. 

See https://redis.io/docs/latest/commands/renamenx/, https://redis.io/docs/latest/commands/rename/
