### ISSUE TITLE
[Feature Request]:Can the scan command be used instead of the keys command to obtain the key list

### ISSUE THREAD

**Issue by JasirVoriya** [RedisInsight/RedisInsight#3706]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
Due to performance reasons, the keys command has been disabled

**How often do you encounter this problem** (Describe how frequently this problem occurs).

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).
![image](https://github.com/user-attachments/assets/635d69c4-1b4c-4ebe-b87a-f38bbd893e7b)

![image](https://github.com/user-attachments/assets/6f814bda-10ae-4603-97dd-3cc9e883c76c)

**Comment by JasirVoriya** [comment]
![image](https://github.com/user-attachments/assets/b49923a9-2b55-477f-843b-65a0c9778d94)

**Comment by ViktarStarastsenka** [comment]
@JasirVoriya , sure, you can use the `SCAN` command to obtain the list of keys.
here is its syntax - https://redis.io/docs/latest/commands/scan/

**Comment by ViktarStarastsenka** [comment]
btw, the "keys to scan setting" is a bit confusing. Here is a description of what it does - https://github.com/RedisInsight/RedisInsight/issues/526#issuecomment-1728437429

the "keys" command errored in your case because it was restricted at the server level.


Please re-open the ticket if the issue still persists.
