### ISSUE TITLE
[Bug]: AppImage: The SUID sandbox helper binary was found, but is not configured correctly.

### ISSUE THREAD

**Issue by Jimbolino** [RedisInsight/RedisInsight#3851]
I've downloaded the latest `Redis-Insight-linux-x86_64.AppImage` from the website.
I'm on a clean ubuntu 24.04.1 install.

output:
```
jim@jim:~/Applications$ ./Redis-Insight-linux-x86_64.AppImage
[43245:0922/145908.668205:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_Redis-fRv5zU/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

**Comment by Jimbolino** [comment]
latest .deb also cannot be run:

```
jim@jim:~/Downloads$ redisinsight 
LaunchProcess: failed to execvp:
/opt/Redis
[43700:0922/150054.089385:FATAL:zygote_host_impl_linux.cc(201)] Check failed: . : Invalid argument (22)
Trace/breakpoint trap (core dumped)
```

**Comment by Jimbolino** [comment]
ok, so the .deb is faulty because it installs into a folder with a space in the name:

```
jim@jim:/opt/Redis Insight$ ./redisinsight 
LaunchProcess: failed to execvp:
/opt/Redis
[44431:0922/150514.546794:FATAL:zygote_host_impl_linux.cc(201)] Check failed: . : Invalid argument (22)
Trace/breakpoint trap (core dumped)

jim@jim:/opt/Redis Insight$ cd ..

jim@jim:/opt$ sudo mv Redis\ Insight/ Redis-Insight

jim@jim:/opt$ cd Redis-Insight/

jim@jim:/opt/Redis-Insight$ ./redisinsight 
15:05:38.079 › Available port: 5530
15:05:38.614 › App starting.....
15:05:38.741 › AppUpdater initialization
```

Is there no automated testing for these releases?

**Comment by ViktarStarastsenka** [comment]
@Jimbolino , for AppImage, you need to either use `--no-sandbox` or ensure that the `/tmp/.mount_Redis-fRv5zU/chrome-sandbox` is owned by root and have the 4755 permission set.

**Comment by Jimbolino** [comment]
how can i ensure the correct permissions are set, if the AppImage creates the folder when its run?

**Comment by abmittra** [comment]
I am receiving the same issue with the .deb and AppImage, is there a fix for this team?
@Jimbolino how did you make it work with the .deb, i am followed your solution and i still am not able to run it in my docker container.

**Comment by ViktarStarastsenka** [comment]
for AppImage this happens because Ubuntu 24.04 has FUSE v3 preinstalled though AppImage works properly only with FUSE2 - [docs.appimage.org/source/user-guide/troubleshooting/fuse.rst at master · AppImage/docs.appimage.org](https://github.com/AppImage/docs.appimage.org/blob/master/source/user-guide/troubleshooting/fuse.rst#setting-up-fuse-2-x-alongside-of-fuse-3-x-on-recent-ubuntu-22-04-debian-and-their-derivatives).
Additionally, Ubuntu 24.04 has a new security approach [Restricted unprivileged user namespaces are coming to Ubuntu 23.10 | Ubuntu](https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces), which can be bypassed by running AppImages with `--no-sandbox` argument at the end

As a solution, you can:
1. Install FUSE2 - [docs.appimage.org/source/user-guide/troubleshooting/fuse.rst at master · AppImage/docs.appimage.org](https://github.com/AppImage/docs.appimage.org/blob/master/source/user-guide/troubleshooting/fuse.rst#setting-up-fuse-2-x-alongside-of-fuse-3-x-on-recent-ubuntu-22-04-debian-and-their-derivatives) 

2. If FUSE can be found now but the app is still not starting - run the app with an additional argument - ./RedisInsight.AppImage `--no-sandbox`.

**Comment by ViktarStarastsenka** [comment]
about Debian - the problem is caused by a space in the application name, which is not supported by electron-builder (https://github.com/electron-userland/electron-builder).
We are working on an alternative solution, but here is a ticket with a temporary workaround for that - https://github.com/RedisInsight/RedisInsight/issues/3871

**Comment by Jimbolino** [comment]
would it not be easier to hardcode the `--no-sandbox` in the `AppRun` script?
its already hardcoded in the `redisinsight.desktop` file...

**Comment by isapir** [comment]
Where can I find the `redisinsight.desktop` file @Jimbolino ?

**Comment by takeseem** [comment]
最简单的方式就是使用：`--no-sandbox`

xubuntu 24.04 参考了 Android Studio 的配置，配置 apparmor
```
echo 'abi <abi/4.0>,
include <tunables/global>
profile redis-insight /data/app/redis/Redis-Insight-*.AppImage flags=(unconfined) {
  userns,
}' | sudo tee /etc/apparmor.d/redis-insight
sudo apparmor_parser -r /etc/apparmor.d/redis-insight
```

application's `redis-insight.desktop`
```
myapp=redis
cd /data/app/$myapp/
echo "
[Desktop Entry]
Name=Redis Insight
Type=Application
Icon=/data/app/$myapp/$myapp.jpeg
Exec=/data/app/$myapp/Redis-Insight-linux-x86_64.AppImage %U
Path=/data/app/$myapp
MimeType=x-scheme-handler/redisinsight;
Categories=Development;
" > redis-insight.desktop
chmod +x redis-insight.desktop
ln -sf "$PWD/redis-insight.desktop" ~/.local/share/applications/

xdg-mime default redis-insight.desktop x-scheme-handler/redisinsight
xdg-open redisinsight://test
```
