### ISSUE TITLE
[Bug]: The connection has timed out, please check the connection details.

### ISSUE THREAD

**Issue by paiky** [RedisInsight/RedisInsight#3901]
**Preconditions** (Any important steps we need to know)
I installed a redis cluster in window for docker, with three masters and three slaves. Each node can be connected (I can connect to the node individually in the console and other clients, like Another redis desktop manager), but I cannot connect to the cluster node on redis insight

**Steps to reproduce** (How to reproduce what you found step by step)
Docker installs redis and turns on cluster mode

**Actual behavior** (A short description of what you found)
I reinstalled a separate redis container in docker and was able to connect via redis insight, but the cluster mode node still failed to connect

**Expected behavior** (A short description of what you expected to find)
Cluster nodes can be connected normally

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
Successfully connected to non-cluster docker container node
![image](https://github.com/user-attachments/assets/1933703f-850a-439e-a69b-cbd87371cc4a)

Successfully connected to the non-cluster local node
![image](https://github.com/user-attachments/assets/325e6f45-3e2c-46dc-ae05-bc5d0cdc9586)

Successfully connected to the cluster docker container node
![image](https://github.com/user-attachments/assets/260de015-60c7-410a-bfc9-67d96032be52)

Successfully connect to cluster docker container nodes or non-cluster container nodes through 【another redis desktop manager】
![image](https://github.com/user-attachments/assets/a7a835f8-4f21-4374-97ee-a7afe70e4354)

Redis insight cannot connect to cluster container nodes
![image](https://github.com/user-attachments/assets/500b73c3-9e48-4ec1-ae38-ced0581ac506)

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

The 6379 port node is redis version 5.0, 6378 and 6001 are redis version 7.4

**Comment by paiky** [comment]
Supplement: I use window11, and the Redis Insight version is the latest 2.58.0

**Comment by ArtemHoruzhenko** [comment]
Seems like `172.19.0.13` is not reachable from your host. 

I assume you was able to connect to your database with another desktop app because you established `standalone` connection for several nodes manually but they are not in a `cluster` mode. Redis Insight was designed to establish connection to all the cluster nodes to have possibility redirect your commands to responsible node automatically. 

I can suggest you to:
1. resolve network issue (make sure that `172.19.0.*` is reachable).
2. use [Redis Insight docker image](https://hub.docker.com/r/redis/redisinsight). You can easy add it to your docker-compose file so Redis cluster database will share the same network with RI

**Comment by paiky** [comment]
It is true that my host cannot directly access the container network. I will consider your suggestion and put redis insight and the container in the same network. Thanks for your answer!
