### ISSUE TITLE
Add Sponsorships

### ISSUE THREAD

**Issue by nikolaydubina** [RedisInsight/RedisInsight#4067]
I don't use Redis cloud offerings. But I have been using redis for many years. This is one of my favorite databases. I would sponsor it if there were an option to do so!

**Comment by LiorKogan** [comment]
@nikolaydubina thank you, Redis is serving thousands of paying customers with [Redis Cloud](https://redis.io/cloud/) and [Redis Software](https://redis.io/enterprise/). We are happy to offer [Redis Community Edition](https://github.com/redis/redis/releases) (that's the name of source-available Redis since v8.0) and Redis Insight to the community for free.

Sponsorship is an excellent way to support early-stage companies and independent developers with no commercial offers. We are way beyond this point!
